name: Network Print & Scan Server
version: "1.4.17"
image: ghcr.io/vtechs-ja/ha-cups-sane-addon
slug: network-print-scan-hub
description: Leverage your Home Assistant host server to network-enable USB printers and scanners. Provides CUPS printing, SANE scanning, and web interface.
url: https://github.com/timrwwatson/ha-cups-sane-addon
arch:
  - aarch64
  - armhf
  - armv7
  - amd64
  - i386
usb: true
init: false
homeassistant_api: true
host_network: true
panel_icon: mdi:printer
icon: icon.png
logo: icon.png
ports:
  631/tcp: 631
  631/udp: 631
  8080/tcp: 8080
ports_description:
  631/tcp: Used by other devices on the local network to post print jobs to this server (TCP)
  631/udp: Used by other devices on the local network to post print jobs to this server (UDP)
  8080/tcp: Used to expose ScanServer web interface (TCP)
ingress: true
ingress_port: 8080
map:
  - config:rw
  - ssl
options:
  printer_support: full
  ocr_languages:
    - eng
schema:
  printer_support: match(minimal|common|full)
  ocr_languages:
    - match(eng|deu|fra|spa|ita|por|nld|rus|jpn|chi_sim|chi_tra|ara)
startup: system
boot: auto
